### ISSUE TITLE
Requirements on tags to succeed with quiz

### ISSUE THREAD

**Issue by onnerby** [Intermezzon/palms.academy#19]
**Is your feature request related to a problem? Please describe.**
When using selection on what questions the user should get in a quiz, it's hard to set the max point to succeed.
We also need to set different requirements on different tags. 

**Describe the solution you'd like**
Be able to set the success limit in percent or point both in total and on different tags.

**Comment by certifikation** [comment]
1. Assign Weights to Tags: Assign different weights to questions based on their tags. Some tags may be considered more important or more difficult, so they should contribute more to the overall score. For example, if you have tags like "Easy," "Medium," and "Hard," questions tagged as "Hard" might contribute more to the overall score than questions tagged as "Easy."

2. Set Tag-specific Requirements: Determine specific requirements for each tag in order to succeed. For example, you might require a higher percentage of correct answers for questions with the "Hard" tag compared to questions with the "Easy" tag.

**Comment by onnerby** [comment]
> 1. Assign Weights to Tags: Assign different weights to questions based on their tags. Some tags may be considered more important or more difficult, so they should contribute more to the overall score. For example, if you have tags like "Easy," "Medium," and "Hard," questions tagged as "Hard" might contribute more to the overall score than questions tagged as "Easy."

Powerful indeed, but there is a risk that this will become unmanageable and very unclear to the administrator how to handle the weighing of the tags. Isn't it easier just to change the `score` on the question to a higher score on harder questions?
Although you need to be aware that you need to score the same way on all questions throughout the system.

> 2. Set Tag-specific Requirements: Determine specific requirements for each tag in order to succeed. For example, you might require a higher percentage of correct answers for questions with the "Hard" tag compared to questions with the "Easy" tag.

Exactly. This is what the issue is about 😄
