### ISSUE TITLE
Automation tool

### ISSUE THREAD

**Issue by onnerby** [Intermezzon/palms.academy#21]
**Is your feature request related to a problem? Please describe.**
We need aa standardised way to make automations like:
 - Send out reminders when
   - You haven't completed your courses in time
   - There is a occasion the next day that you signed up for
 - Publish/unpublish courses at an exact time
 - Send out reports to people (ie weekly report)
 - etc

**Describe the solution you'd like**
Make a tool to build this kind of automated flows.

**Comment by MarieEklund** [comment]
These tickets belong to Automatisation project (due to excelsheet for Humana February 2024)

1) First booking date - Events have a last booking date but can we add a first booking date? Sometimes educators don't want the participants to be able to book themselves on a event until they have finished another earlier event. We can't use the lock function because some courses have different events for different people. 

2) Message of new educations: In automatisation project it will be possible to make rules on how to reminded;This is possible today

3) Automatic e-mail to the user when account is made in the learning portal

4) When it is time for a person with delegetion to perform the education again, the reminder should go to the nurse, not only to the manager. 

5) Automatic reminder to participants when they are supposed to do "repetition-course" that is not the same as the original course

6) Keep track on performed educations and certificates (a bit unclear what this is)

7) Notification to manager when employee signs up for education

8) Autmatic message to education owner

**Comment by onnerby** [comment]
@MarieEklund 
I've broken out some of the issues from the list to own issues.

> 1. First booking date - Events have a last booking date but can we add a first booking date? Sometimes educators don't want the participants to be able to book themselves on a event until they have finished another earlier event. We can't use the lock function because some courses have different events for different people.
#25

> 2. Message of new educations: In automatisation project it will be possible to make rules on how to reminded;This is possible today
#26 

> 3. Automatic e-mail to the user when account is made in the learning portal
#30

> 4. When it is time for a person with delegetion to perform the education again, the reminder should go to the nurse, not only to the manager.
#32

> 5. Automatic reminder to participants when they are supposed to do "repetition-course" that is not the same as the original course
#32

> 6. Keep track on performed educations and certificates (a bit unclear what this is)
> 7. Notification to manager when employee signs up for education
#33 

> 8. Autmatic message to education owner
#34
